# The Site Configuration
theme: jekyll-theme-chirpy
lang: ko-KR
timezone: Asia/Seoul
title: "대충 살아가는 게임개발자"
tagline: "이글루스와 티스토리를 정처없이 떠돌아다니다 여기로 옮겨옴"
description: >-
  TA 대마왕의 대충 살아가는 게임개발자 블로그

url: "https://jpcorps.github.io"
github:
  username: jpcorps

social:
  name: 대마왕
  email: jpcorp@hanmail.net
  links:
    - https://github.com/jpcorps

theme_mode: 
avatar: /Face.png
toc: true

comments:
  provider: giscus
  giscus:
    repo: jpcorps/jpcorps.github.io
    repo_id: R_kgDOSOA18Q
    category: General
    category_id: DIC_kwDOSOA18c4C7-G6
    mapping: pathname
    strict: 0
    input_position: bottom
    lang: ko
    reactions_enabled: 1

paginate: 10
baseurl: ""

paginate: 10
baseurl: ""
excerpt_separator: "<!-- more -->"  # 이 줄을 추가하세요!

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  # 1. 포스트 설정 (주소 충돌 방지를 위해 수정)
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:year-:month-:day-:title/ # 여기만 날짜를 추가!

  # 2. 탭 설정 (기존처럼 깔끔하게 유지)
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  
  # 2010년 이전의 아주 오래된 글들은 검색 엔진에서 제외하여 빌드 속도 향상
  - scope:
      path: "_posts/2006" # 폴더 구조가 년도별로 되어 있다면 유용합니다
    values:
      search: false
  - scope:
      path: "_posts/2007"
    values:
      search: false
  - scope:
      path: "_posts/2008"
    values:
      search: false
  - scope:
      path: "_posts/2009"
    values:
      search: false
      

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
